name: Build

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build MouseRift
        run: >-
          mkdir -p log && xcodebuild
          -project MouseRift.xcodeproj
          -scheme MouseRift
          -configuration Development
          CODE_SIGNING_ALLOWED=NO
          build
